### ISSUE TITLE
validateVat always returning status:undefined

### ISSUE THREAD

**Issue by julianCast** [chargebee/chargebee-js-types#9]
When running this example:
https://www.chargebee.com/checkout-portal-docs/eu-vat-validation-function.html#integration
```js
 let cbInstance = Chargebee.getInstance();
  charegbeeInstance.load('functions').then(() => {
    const payload = {
          country: "DE",
          vat_number: "811569869",
        }
    cbInstance.vat.validateVat(payload).then(data => {
      // Your code here
    }).catch(err => {
      // Your code here
    })
  });
  ```

I'm always getting  `{status: undefined}` as result.

Playground as example https://jsfiddle.net/r27panuv/

**Comment by julianCast** [comment]
Solved! VAT validation needed to be enabled in the admin panel. The documentation is missing that. Thanks!

**Comment by cb-dinesh** [comment]
cc: @cb-nimithajalal
